spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: admission-service
          uri: lb://ADMISSION-SERVICE
          predicates:
            - Path=/admission/**

#id - used for calling from internal API
#URI - same as spring-app-name (mandatory)
#path - indicates @RequestMapping

server:
  port: 8989


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost